import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'carne', loadChildren: './recetas/carne/carne.module#CarnePageModule' },
  { path: 'pollo', loadChildren: './recetas/pollo/pollo.module#PolloPageModule' },
  { path: 'pescado', loadChildren: './recetas/pescado/pescado.module#PescadoPageModule' },
  { path: 'fajitas-de-res', loadChildren: './recetas/carne/recetario/fajitas-de-res/fajitas-de-res.module#FajitasDeResPageModule' },  { path: 'ensalada-pollo-bufaflo', loadChildren: './recetas/pollo/recetario/ensalada-pollo-bufaflo/ensalada-pollo-bufaflo.module#EnsaladaPolloBufafloPageModule' },
  { path: 'postres', loadChildren: './recetas/postres/postres.module#PostresPageModule' },
  { path: 'bizcocho-naranja', loadChildren: './recetas/postres/recetario/bizcocho-naranja/bizcocho-naranja.module#BizcochoNaranjaPageModule' },
  { path: 'chili', loadChildren: './recetas/carne/recetario/chili/chili.module#ChiliPageModule' },
  { path: 'lasana', loadChildren: './recetas/carne/recetario/lasana/lasana.module#LasanaPageModule' },
  { path: 'muffins', loadChildren: './recetas/carne/recetario/muffins/muffins.module#MuffinsPageModule' },
  { path: 'pimientos', loadChildren: './recetas/carne/recetario/pimientos/pimientos.module#PimientosPageModule' },
  { path: 'ensalada', loadChildren: './recetas/carne/recetario/ensalada/ensalada.module#EnsaladaPageModule' },
  { path: 'pasta', loadChildren: './recetas/carne/recetario/pasta/pasta.module#PastaPageModule' },
  { path: 'filete', loadChildren: './recetas/carne/recetario/filete/filete.module#FiletePageModule' },
  { path: 'gratinado', loadChildren: './recetas/carne/recetario/gratinado/gratinado.module#GratinadoPageModule' },
  { path: 'filete-huevo', loadChildren: './recetas/carne/recetario/filete-huevo/filete-huevo.module#FileteHuevoPageModule' },
  { path: 'solomillo', loadChildren: './recetas/carne/recetario/solomillo/solomillo.module#SolomilloPageModule' },
  { path: 'pescado-arroz', loadChildren: './recetas/pescado/recetario/pescado-arroz/pescado-arroz.module#PescadoArrozPageModule' },
  { path: 'pescado-mostaza', loadChildren: './recetas/pescado/recetario/pescado-mostaza/pescado-mostaza.module#PescadoMostazaPageModule' },
  { path: 'hamburguesa', loadChildren: './recetas/pescado/recetario/hamburguesa/hamburguesa.module#HamburguesaPageModule' },
  { path: 'pescado-gratinado', loadChildren: './recetas/pescado/recetario/pescado-gratinado/pescado-gratinado.module#PescadoGratinadoPageModule' },
  { path: 'sopa-picante', loadChildren: './recetas/pescado/recetario/sopa-picante/sopa-picante.module#SopaPicantePageModule' },
  { path: 'pescado-frito', loadChildren: './recetas/pescado/recetario/pescado-frito/pescado-frito.module#PescadoFritoPageModule' },
  { path: 'huevos', loadChildren: './recetas/pescado/recetario/huevos/huevos.module#HuevosPageModule' },
  { path: 'ensalada-nizarda', loadChildren: './recetas/pescado/recetario/ensalada-nizarda/ensalada-nizarda.module#EnsaladaNizardaPageModule' },
  { path: 'rollito', loadChildren: './recetas/pescado/recetario/rollito/rollito.module#RollitoPageModule' },
  { path: 'ensalada-toscana', loadChildren: './recetas/pescado/recetario/ensalada-toscana/ensalada-toscana.module#EnsaladaToscanaPageModule' },
  { path: 'sesamo', loadChildren: './recetas/pollo/recetario/sesamo/sesamo.module#SesamoPageModule' },
  { path: 'patatas', loadChildren: './recetas/pollo/recetario/patatas/patatas.module#PatatasPageModule' },
  { path: 'mediterraneo', loadChildren: './recetas/pollo/recetario/mediterraneo/mediterraneo.module#MediterraneoPageModule' },
  { path: 'mango', loadChildren: './recetas/pollo/recetario/mango/mango.module#MangoPageModule' },
  { path: 'alfredo', loadChildren: './recetas/pollo/recetario/alfredo/alfredo.module#AlfredoPageModule' },
  { path: 'quinoa', loadChildren: './recetas/pollo/recetario/quinoa/quinoa.module#QuinoaPageModule' },
  { path: 'burrito', loadChildren: './recetas/pollo/recetario/burrito/burrito.module#BurritoPageModule' },
  { path: 'sopa-blanca', loadChildren: './recetas/pollo/recetario/sopa-blanca/sopa-blanca.module#SopaBlancaPageModule' },
  { path: 'sopa-pollo', loadChildren: './recetas/pollo/recetario/sopa-pollo/sopa-pollo.module#SopaPolloPageModule' },
  { path: 'garbanzoa', loadChildren: './recetas/pollo/recetario/garbanzoa/garbanzoa.module#GarbanzoaPageModule' },
  { path: 'comer-bien', loadChildren: './tab2/comer-bien/comer-bien.module#ComerBienPageModule' },
  { path: 'dormir-bien', loadChildren: './tab2/dormir-bien/dormir-bien.module#DormirBienPageModule' },
  { path: 'ejercicio', loadChildren: './tab2/ejercicio/ejercicio.module#EjercicioPageModule' },
  { path: 'albondigas', loadChildren: './recetas/carne/recetariov2/albondigas/albondigas.module#AlbondigasPageModule' },
  { path: 'arroz-verduras', loadChildren: './recetas/carne/recetariov2/arroz-verduras/arroz-verduras.module#ArrozVerdurasPageModule' },
  { path: 'bolonesa', loadChildren: './recetas/carne/recetariov2/bolonesa/bolonesa.module#BolonesaPageModule' },
  { path: 'chuletas', loadChildren: './recetas/carne/recetariov2/chuletas/chuletas.module#ChuletasPageModule' },
  { path: 'coreano', loadChildren: './recetas/carne/recetariov2/coreano/coreano.module#CoreanoPageModule' },
  { path: 'dumplings', loadChildren: './recetas/carne/recetariov2/dumplings/dumplings.module#DumplingsPageModule' },
  { path: 'ensalada-picante', loadChildren: './recetas/carne/recetariov2/ensalada-picante/ensalada-picante.module#EnsaladaPicantePageModule' },
  { path: 'goulash', loadChildren: './recetas/carne/recetariov2/goulash/goulash.module#GoulashPageModule' },
  { path: 'lowcarb', loadChildren: './recetas/carne/recetariov2/lowcarb/lowcarb.module#LowcarbPageModule' },
  { path: 'mexicano', loadChildren: './recetas/carne/recetariov2/mexicano/mexicano.module#MexicanoPageModule' },
  { path: 'portobello', loadChildren: './recetas/carne/recetariov2/portobello/portobello.module#PortobelloPageModule' },
  { path: 'rabano', loadChildren: './recetas/carne/recetariov2/rabano/rabano.module#RabanoPageModule' },
  { path: 'salados', loadChildren: './recetas/carne/recetariov2/salados/salados.module#SaladosPageModule' },
  { path: 'thai', loadChildren: './recetas/pescado/recetariov2/thai/thai.module#ThaiPageModule' },
  { path: 'batatas', loadChildren: './recetas/pescado/recetariov2/batatas/batatas.module#BatatasPageModule' },
  { path: 'palitos', loadChildren: './recetas/pescado/recetariov2/palitos/palitos.module#PalitosPageModule' },
  { path: 'vapor', loadChildren: './recetas/pescado/recetariov2/vapor/vapor.module#VaporPageModule' },
  { path: 'feta', loadChildren: './recetas/pescado/recetariov2/feta/feta.module#FetaPageModule' },
  { path: 'coliflor', loadChildren: './recetas/pescado/recetariov2/coliflor/coliflor.module#ColiflorPageModule' },
  { path: 'gambas', loadChildren: './recetas/pescado/recetariov2/gambas/gambas.module#GambasPageModule' },
  { path: 'pepino', loadChildren: './recetas/pescado/recetariov2/pepino/pepino.module#PepinoPageModule' },
  { path: 'tost-huevo', loadChildren: './recetas/pescado/recetariov2/tost-huevo/tost-huevo.module#TostHuevoPageModule' },
  { path: 'ahumado', loadChildren: './recetas/pescado/recetariov2/ahumado/ahumado.module#AhumadoPageModule' },
  { path: 'crujiente', loadChildren: './recetas/pollo/recetariov2/crujiente/crujiente.module#CrujientePageModule' },
  { path: 'hierbas', loadChildren: './recetas/pollo/recetariov2/hierbas/hierbas.module#HierbasPageModule' },
  { path: 'champinones', loadChildren: './recetas/pollo/recetariov2/champinones/champinones.module#ChampinonesPageModule' },
  { path: 'p-coreana', loadChildren: './recetas/pollo/recetariov2/p-coreana/p-coreana.module#PCoreanaPageModule' },
  { path: 'parrilla', loadChildren: './recetas/pollo/recetariov2/parrilla/parrilla.module#ParrillaPageModule' },
  { path: 'coco', loadChildren: './recetas/pollo/recetariov2/coco/coco.module#CocoPageModule' },
  { path: 'caprese', loadChildren: './recetas/pollo/recetariov2/caprese/caprese.module#CapresePageModule' },
  { path: 'nueces', loadChildren: './recetas/pollo/recetariov2/nueces/nueces.module#NuecesPageModule' },
  { path: 'miel', loadChildren: './recetas/pollo/recetariov2/miel/miel.module#MielPageModule' },
  { path: 'wraps', loadChildren: './recetas/pollo/recetariov2/wraps/wraps.module#WrapsPageModule' },

  
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
